### ISSUE TITLE
Discrepancy in calculated scores for TableS2 in Bottcher's paper

### ISSUE THREAD

**Issue by jun-li-2020** [ccsb-scripps/bottchscore#2]
This is a nice web app (https://forlilab.org/services/bottcher/).  however, during a recent check-up of a few compounds published in Bottcher's paper (https://pubs.acs.org/doi/abs/10.1021/acs.jcim.5b00723) SI section.  The last three compounds in the table S2 showed the following differences in Cm:

1,2-Dimethylcyclopropane CC1CC1C   26.51  (15.75 in original SI)
1,1-Dimethylpropane CCC(C)C 17.17 (16.00 in original SI)
Bicyclo[2.1.0]pentane C1CC2CC12 30.51  (19.75 in original SI)

 I checked both web app and the python code in the Github, both gave the same results here, seems like not an error in depolyment of the code.  The rest of the compounds in this table S2 matched well.  Besides, I also looked into the amino acids and sugars under Table S6, it is interesting that in order to match the original results, amino acids need to be input as the zwitterion SMILES. However, I still find Arginine could not be matched (142.58 vs the original 129.65).  Sugar needs to be input as the pyranose and furanose ring SMILES to get matched.  Ribofuranose is very close (219.10 vs the original 221.10).  Don't know if these observations have been reported before or not, just want to alert you guys.  Thanks,

**Comment by sforli** [comment]
@jun-li-2020 thank you for reporting the issues!

First a premise. We had a nice discussion with Thomas Böttcher about some of the discrepancies you mentioned and it seems there might be a few inaccuracies in some of the table values, especially for amino acids and sugars, depending on which representation one chooses, and how diasterotopic groups might be treated.
About the specific discrepancies in the Table S2, though, I'm not sure where they come from, even after looking at the single terms breakdown.
If you have any suggestions, please let me know.

**Comment by jun-li-2020** [comment]
Thank you very much Stefano!  This is great that you have contacted Thomas Böttcher to verify the results posted in his SI and also confirmed a few inaccuracies in some of the table values here.  I do not have any ideas to explain the differences of the three values in the table S2.  As an alternative suggestion, I noticed Schrier's group(https://www.fordham.edu/info/28651/joshua_schrier) has also recently posted their Mathematica version of the Bottcher score (see here in github, https://github.com/wrborrelli/MolecularComplexityMA).  I could not verify these three compounds using their tool.  It might be interesting to have them double check the results.  Just a thought.

**Comment by sforli** [comment]
I think comparing the two implementations is a great idea. I'm sure there lots of bugs lurking in the code, and this sounds like an efficient way to make them apparent.
